import { useState } from "react";
import { Lang } from "@/types";
import { InvestorProfile } from "@/hooks/useInvestorProfile";

const ONBOARDING_KEY = "ais_onboarded_v1";

export function shouldShowOnboarding(): boolean {
  try { return !localStorage.getItem(ONBOARDING_KEY); } catch { return false; }
}

export function markOnboarded() {
  try { localStorage.setItem(ONBOARDING_KEY, "1"); } catch {}
}

interface Props {
  lang: Lang;
  profile: InvestorProfile;
  onSaveProfile: (p: InvestorProfile) => void;
  onClose: () => void;
  onAnalyze?: (ticker: string) => void;
}

const DISCLAIMER = {
  ru: "Анализ создан искусственным интеллектом и не является инвестиционной рекомендацией. Все инвестиционные решения принимаются самостоятельно и на собственный риск.",
  en: "Analysis is generated by AI and does not constitute investment advice. All investment decisions are made independently and at your own risk.",
};

function OptionBtn({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) {
  return (
    <button
      onClick={onClick}
      style={{
        background: active ? "var(--border)" : "var(--border2)",
        border: `1px solid ${active ? "rgba(201,168,76,0.5)" : "var(--border2)"}`,
        color: active ? "#c9a84c" : "#555568",
        borderRadius: 7, padding: "7px 14px", cursor: "pointer",
        fontSize: 12, fontFamily: "monospace", transition: "all 0.15s",
      }}
    >{children}</button>
  );
}

function StepDots({ current }: { current: number }) {
  return (
    <div style={{ display: "flex", justifyContent: "center", gap: 8, marginBottom: 22 }}>
      {[0, 1, 2].map(i => (
        <div key={i} style={{ width: i === current ? 20 : 6, height: 6, borderRadius: 3, background: i <= current ? "#c9a84c" : "var(--border2)", transition: "all 0.3s" }} />
      ))}
    </div>
  );
}

export function OnboardingModal({ lang, profile, onSaveProfile, onClose, onAnalyze }: Props) {
  const ru = lang !== "en";
  const [step, setStep] = useState(0);
  const [p, setP] = useState<InvestorProfile>(profile);
  const [firstTicker, setFirstTicker] = useState("");

  const handleFinish = () => {
    onSaveProfile(p);
    markOnboarded();
    if (firstTicker.trim() && onAnalyze) onAnalyze(firstTicker.trim().toUpperCase());
    onClose();
  };

  const cardStyle: React.CSSProperties = {
    background: "var(--bg2)",
    border: "1px solid rgba(201,168,76,0.25)",
    borderRadius: 16,
    padding: "32px 28px",
    maxWidth: 480,
    width: "100%",
    animation: "fadeUp 0.3s ease both",
    maxHeight: "90vh",
    overflowY: "auto",
  };

  return (
    <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.85)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 16 }}>

      {/* Step 0 — Welcome + disclaimer */}
      {step === 0 && (
        <div style={cardStyle}>
          <div style={{ textAlign: "center", marginBottom: 22 }}>
            <div style={{ fontSize: 32, marginBottom: 8 }}>◎</div>
            <div style={{ color: "#c9a84c", fontSize: 12, letterSpacing: "0.2em", fontFamily: "monospace", marginBottom: 6 }}>
              INVESTMENT INTELLIGENCE SYSTEM
            </div>
            <div style={{ color: "var(--text2)", fontSize: 13 }}>
              {ru ? "Добро пожаловать в Инвестиционный Аналитик" : "Welcome to Investment Analyst"}
            </div>
          </div>

          <StepDots current={0} />

          <div style={{ display: "flex", flexDirection: "column", gap: 14, marginBottom: 20 }}>
            {[
              { icon: "🔍", title: ru ? "Анализ любого актива" : "Analyze any asset", desc: ru ? "AAPL, Bitcoin, Tesla, Nike — оценка, тренды 10 лет, волны Кондратьева, техника, сентимент." : "AAPL, Bitcoin, Tesla, Nike — valuation, 10-year trends, Kondratiev waves, technicals, sentiment." },
              { icon: "💼", title: ru ? "Портфель и вотчлист" : "Portfolio & Watchlist", desc: ru ? "Отслеживайте P&L. Portfolio Intelligence анализирует весь портфель целиком." : "Track P&L. Portfolio Intelligence analyzes the entire portfolio at once." },
              { icon: "⚡", title: ru ? "Умный кэш и история" : "Smart cache & history", desc: ru ? "Результаты сохраняются на 2 часа. История позволяет быстро вернуться к любому активу." : "Results cached for 2 hours. History lets you quickly return to any asset." },
            ].map(({ icon, title, desc }) => (
              <div key={title} style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
                <div style={{ fontSize: 22, flexShrink: 0, marginTop: 2 }}>{icon}</div>
                <div>
                  <div style={{ color: "var(--text)", fontSize: 13, fontWeight: 700, marginBottom: 3 }}>{title}</div>
                  <div style={{ color: "#666678", fontSize: 11, lineHeight: 1.6 }}>{desc}</div>
                </div>
              </div>
            ))}
          </div>

          <div style={{ background: "rgba(255,165,0,0.04)", border: "1px solid rgba(255,165,0,0.2)", borderRadius: 8, padding: "12px 14px", marginBottom: 18, borderLeft: "2px solid rgba(255,165,0,0.5)" }}>
            <div style={{ color: "#999", fontSize: 11, fontFamily: "monospace", lineHeight: 1.6 }}>
              ⚠ {DISCLAIMER[lang] ?? DISCLAIMER.ru}
            </div>
          </div>

          <button
            onClick={() => setStep(1)}
            style={{ width: "100%", background: "linear-gradient(135deg,#c9a84c,#8b6810)", border: "none", borderRadius: 10, padding: "12px 24px", color: "var(--bg)", fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "monospace" }}
          >
            {ru ? "Принимаю и продолжаю →" : "I accept & continue →"}
          </button>
        </div>
      )}

      {/* Step 1 — Investor profile */}
      {step === 1 && (
        <div style={cardStyle}>
          <div style={{ textAlign: "center", marginBottom: 18 }}>
            <div style={{ fontSize: 28, marginBottom: 8 }}>👤</div>
            <div style={{ color: "#c9a84c", fontSize: 10, letterSpacing: "0.2em", fontFamily: "monospace", marginBottom: 6 }}>
              {ru ? "ШАГ 2 ИЗ 3" : "STEP 2 OF 3"}
            </div>
            <div style={{ color: "var(--text)", fontSize: 15, fontWeight: 700, marginBottom: 4 }}>
              {ru ? "Настройте профиль инвестора" : "Set your investor profile"}
            </div>
            <div style={{ color: "#666678", fontSize: 11 }}>
              {ru ? "ИИ учтёт ваш профиль в анализе" : "AI will tailor analysis to your profile"}
            </div>
          </div>

          <StepDots current={1} />

          <div style={{ marginBottom: 16 }}>
            <div style={{ color: "#666678", fontSize: 10, fontFamily: "monospace", letterSpacing: "0.1em", marginBottom: 8 }}>{ru ? "ГОРИЗОНТ" : "HORIZON"}</div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              {(["short", "medium", "long"] as const).map(h => (
                <OptionBtn key={h} active={p.horizon === h} onClick={() => setP({ ...p, horizon: h })}>
                  {ru ? { short: "Краткосрочный", medium: "Среднесрочный", long: "Долгосрочный" }[h] : { short: "Short-term", medium: "Mid-term", long: "Long-term" }[h]}
                </OptionBtn>
              ))}
            </div>
          </div>

          <div style={{ marginBottom: 16 }}>
            <div style={{ color: "#666678", fontSize: 10, fontFamily: "monospace", letterSpacing: "0.1em", marginBottom: 8 }}>{ru ? "РИСК" : "RISK"}</div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              {(["conservative", "moderate", "aggressive"] as const).map(r => (
                <OptionBtn key={r} active={p.risk === r} onClick={() => setP({ ...p, risk: r })}>
                  {ru ? { conservative: "Консервативный", moderate: "Умеренный", aggressive: "Агрессивный" }[r] : { conservative: "Conservative", moderate: "Moderate", aggressive: "Aggressive" }[r]}
                </OptionBtn>
              ))}
            </div>
          </div>

          <div style={{ marginBottom: 22 }}>
            <div style={{ color: "#666678", fontSize: 10, fontFamily: "monospace", letterSpacing: "0.1em", marginBottom: 8 }}>{ru ? "ЦЕЛЬ" : "GOAL"}</div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              {(["income", "growth", "speculation"] as const).map(g => (
                <OptionBtn key={g} active={p.goal === g} onClick={() => setP({ ...p, goal: g })}>
                  {ru ? { income: "Доход", growth: "Рост капитала", speculation: "Спекуляции" }[g] : { income: "Income", growth: "Growth", speculation: "Speculation" }[g]}
                </OptionBtn>
              ))}
            </div>
          </div>

          <div style={{ display: "flex", gap: 10 }}>
            <button onClick={() => setStep(0)} style={{ background: "var(--border2)", border: "1px solid var(--border2)", borderRadius: 10, padding: "12px 16px", color: "#555568", fontSize: 13, cursor: "pointer", fontFamily: "monospace" }}>←</button>
            <button onClick={() => setStep(2)} style={{ flex: 1, background: "linear-gradient(135deg,#c9a84c,#8b6810)", border: "none", borderRadius: 10, padding: "12px", color: "var(--bg)", fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "monospace" }}>
              {ru ? "Сохранить →" : "Save →"}
            </button>
          </div>
        </div>
      )}

      {/* Step 2 — Ready */}
      {step === 2 && (
        <div style={cardStyle}>
          <div style={{ textAlign: "center", marginBottom: 18 }}>
            <div style={{ fontSize: 40, marginBottom: 10 }}>🚀</div>
            <div style={{ color: "#c9a84c", fontSize: 10, letterSpacing: "0.2em", fontFamily: "monospace", marginBottom: 6 }}>
              {ru ? "ШАГ 3 ИЗ 3" : "STEP 3 OF 3"}
            </div>
            <div style={{ color: "var(--text)", fontSize: 16, fontWeight: 700, marginBottom: 8 }}>
              {ru ? "Всё готово!" : "You're all set!"}
            </div>
            <div style={{ color: "#666678", fontSize: 12, lineHeight: 1.7 }}>
              {ru
                ? "Профиль сохранён. Введите тикер или название актива и нажмите «Анализировать»."
                : "Profile saved. Enter a ticker or asset name and click «Analyze»."}
            </div>
          </div>

          <StepDots current={2} />

          <div style={{ marginBottom: 22 }}>
            <div style={{ color: "#666678", fontSize: 10, fontFamily: "monospace", letterSpacing: "0.1em", marginBottom: 10 }}>
              {ru ? "ВВЕДИТЕ ПЕРВЫЙ АКТИВ ДЛЯ АНАЛИЗА" : "ENTER YOUR FIRST ASSET TO ANALYZE"}
            </div>
            <div style={{ display: "flex", gap: 8, marginBottom: 10 }}>
              <input
                value={firstTicker}
                onChange={e => setFirstTicker(e.target.value.toUpperCase())}
                onKeyDown={e => { if (e.key === "Enter") handleFinish(); }}
                placeholder={ru ? "AAPL, BTC, SBER..." : "AAPL, BTC, TSLA..."}
                style={{ flex: 1, background: "var(--border2)", border: "1px solid rgba(201,168,76,0.3)", borderRadius: 8, padding: "10px 14px", color: "var(--text)", fontSize: 14, fontFamily: "monospace", outline: "none" }}
              />
            </div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              {(ru ? ["AAPL", "SBER", "BTC", "NVDA", "LKOH"] : ["AAPL", "BTC", "NVDA", "TSLA", "SPY"]).map(ticker => (
                <button key={ticker} onClick={() => setFirstTicker(ticker)}
                  style={{ background: "rgba(201,168,76,0.06)", border: "1px solid rgba(201,168,76,0.2)", borderRadius: 20, padding: "4px 14px", color: "#c9a84c88", fontSize: 12, fontFamily: "monospace", cursor: "pointer" }}>
                  {ticker}
                </button>
              ))}
            </div>
          </div>

          {/* Profile summary */}
          <div style={{ background: "rgba(201,168,76,0.04)", border: "1px solid rgba(201,168,76,0.15)", borderRadius: 8, padding: "10px 14px", marginBottom: 20 }}>
            <div style={{ color: "#444458", fontSize: 9, fontFamily: "monospace", letterSpacing: "0.1em", marginBottom: 6 }}>
              {ru ? "ВАШ ПРОФИЛЬ" : "YOUR PROFILE"}
            </div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              {[
                ru ? { short: "Краткосрочный", medium: "Среднесрочный", long: "Долгосрочный" }[p.horizon] : { short: "Short-term", medium: "Mid-term", long: "Long-term" }[p.horizon],
                ru ? { conservative: "Консервативный", moderate: "Умеренный", aggressive: "Агрессивный" }[p.risk] : { conservative: "Conservative", moderate: "Moderate", aggressive: "Aggressive" }[p.risk],
                ru ? { income: "Доход", growth: "Рост", speculation: "Спекуляции" }[p.goal] : { income: "Income", growth: "Growth", speculation: "Speculation" }[p.goal],
              ].map(label => (
                <span key={label} style={{ background: "rgba(201,168,76,0.1)", border: "1px solid rgba(201,168,76,0.25)", borderRadius: 20, padding: "2px 10px", color: "#c9a84c", fontSize: 10, fontFamily: "monospace" }}>{label}</span>
              ))}
            </div>
          </div>

          <div style={{ display: "flex", gap: 10 }}>
            <button onClick={() => setStep(1)} style={{ background: "var(--border2)", border: "1px solid var(--border2)", borderRadius: 10, padding: "12px 16px", color: "#555568", fontSize: 13, cursor: "pointer", fontFamily: "monospace" }}>←</button>
            <button onClick={handleFinish} style={{ flex: 1, background: "linear-gradient(135deg,#c9a84c,#8b6810)", border: "none", borderRadius: 10, padding: "12px", color: "var(--bg)", fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "monospace" }}>
              {firstTicker.trim()
                ? (ru ? `Анализировать ${firstTicker} →` : `Analyze ${firstTicker} →`)
                : (ru ? "Начать →" : "Start →")}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
