import { AnalysisData } from "@/types";

function safeUrl(u: unknown): string {
  if (typeof u !== "string" || !u) return "#";
  try {
    const p = new URL(u);
    return ["https:", "http:"].includes(p.protocol) ? u : "#";
  } catch { return "#"; }
}

export function buildMarkdown(data: AnalysisData, lang: "ru" | "en"): string {
  const ru = lang === "ru";
  const lines: string[] = [];

  const h1 = (s: string) => `# ${s}`;
  const h2 = (s: string) => `## ${s}`;
  const row = (label: string, value: string | number | null | undefined) =>
    value != null && value !== "" ? `**${label}:** ${value}` : null;

  // Header
  lines.push(h1(`${data.asset?.ticker} — ${data.asset?.name}`));
  if (data.dataAsOf) lines.push(ru ? `> Данные на: ${data.dataAsOf}` : `> Data as of: ${data.dataAsOf}`);
  lines.push("");

  // Recommendation
  lines.push(h2(ru ? "РЕКОМЕНДАЦИЯ" : "RECOMMENDATION"));
  const action = (data.recommendation?.action ?? "").toUpperCase();
  lines.push(`**${action}**`);
  if (data.recommendation?.confidence) lines.push(row(ru ? "Уверенность" : "Confidence", data.recommendation.confidence) ?? "");
  if (data.recommendation?.timeHorizon) lines.push(row(ru ? "Горизонт" : "Horizon", data.recommendation.timeHorizon) ?? "");
  if (data.recommendation?.summary) lines.push("", data.recommendation.summary);
  if (data.recommendation?.keyPoints?.length) {
    lines.push("", ru ? "**Ключевые тезисы:**" : "**Key points:**");
    data.recommendation.keyPoints.forEach((p, i) => lines.push(`${i + 1}. ${p}`));
  }
  lines.push("");

  // Valuation
  if (data.valuation) {
    lines.push(h2(ru ? "ОЦЕНКА СТОИМОСТИ" : "VALUATION"));
    const cur = data.valuation.currency || "$";
    if (data.valuation.currentPrice != null) lines.push(row(ru ? "Текущая цена" : "Current price", `${cur}${data.valuation.currentPrice}`) ?? "");
    if (data.valuation.fairPrice != null) lines.push(row(ru ? "Справедливая цена" : "Fair price", `${cur}${data.valuation.fairPrice}`) ?? "");
    if (data.valuation.marginOfSafety != null) lines.push(row(ru ? "Запас безопасности" : "Margin of safety", `${data.valuation.marginOfSafety}%`) ?? "");
    if (data.valuation.growthPotential != null) lines.push(row(ru ? "Потенциал роста" : "Growth potential", `${data.valuation.growthPotential > 0 ? "+" : ""}${data.valuation.growthPotential}%`) ?? "");
    lines.push("");
  }

  // Action zones
  const rec = data.recommendation;
  if (rec && (rec.buyZoneLow || rec.sellTarget || rec.stopLoss)) {
    lines.push(h2(ru ? "ПЛАН ДЕЙСТВИЙ" : "ACTION PLAN"));
    const cur = data.valuation?.currency || "$";
    if (rec.buyZoneLow) lines.push(row(ru ? "Зона покупки" : "Buy zone", `${cur}${rec.buyZoneLow}–${rec.buyZoneHigh ?? rec.buyZoneLow}`) ?? "");
    if (rec.sellTarget) lines.push(row(ru ? "Цель" : "Target", `${cur}${rec.sellTarget}`) ?? "");
    if (rec.stopLoss) lines.push(row(ru ? "Стоп-лосс" : "Stop-loss", `${cur}${rec.stopLoss}`) ?? "");
    lines.push("");
  }

  // Risk
  if (data.riskProfile) {
    lines.push(h2(ru ? "РИСК" : "RISK"));
    lines.push(row(ru ? "Уровень" : "Level", data.riskProfile.score) ?? "");
    lines.push(row(ru ? "Волатильность" : "Volatility", data.riskProfile.volatility) ?? "");
    if (data.riskProfile.downsideRisk) lines.push(row(ru ? "Просадка" : "Downside", data.riskProfile.downsideRisk) ?? "");
    lines.push("");
  }

  // Kondratiev
  if (data.kondratiev) {
    lines.push(h2(ru ? "ВОЛНЫ КОНДРАТЬЕВА" : "KONDRATIEV WAVES"));
    lines.push(row(ru ? "Фаза" : "Phase", data.kondratiev.currentPhase) ?? "");
    if (data.kondratiev.phaseDescription) lines.push("", data.kondratiev.phaseDescription);
    if (data.kondratiev.kondratievConclusion) lines.push("", `_${data.kondratiev.kondratievConclusion}_`);
    lines.push("");
  }

  // Technical
  if (data.technical) {
    lines.push(h2(ru ? "ТЕХНИЧЕСКИЙ АНАЛИЗ" : "TECHNICAL ANALYSIS"));
    lines.push(row(ru ? "Тренд" : "Trend", data.technical.trend) ?? "");
    if (data.technical.rsi != null) lines.push(row("RSI", `${data.technical.rsi} (${data.technical.rsiStatus ?? ""})`) ?? "");
    lines.push("");
  }

  // Sources
  if (data.sources?.length) {
    lines.push(h2(ru ? "ИСТОЧНИКИ" : "SOURCES"));
    data.sources.forEach((s) => lines.push(`- [${s.name}](${safeUrl(s.url)})${s.date ? ` — ${s.date}` : ""}`));
    lines.push("");
  }

  lines.push("---");
  lines.push(ru ? "_Создано в Инвестиционном Аналитике_" : "_Generated by Investment Analyst_");

  return lines.filter((l) => l !== null).join("\n");
}
